import { library, config } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import {
  faBook,
  faCode,
  faDatabase,
  faEnvelope,
  faFile,
  faFlag,
  faGraduationCap,
  faHome,
  faList,
  faMapMarkerAlt,
  faMicrochip,
  faProjectDiagram,
  faServer,
  faTerminal,
  faLock,
} from "@fortawesome/free-solid-svg-icons";
import {
  faAngular,
  faDiscord,
  faDocker,
  faGitAlt,
  faGithub,
  faGithubSquare,
  faGitlab,
  faJava,
  faJs,
  faLinkedin,
  faLinux,
  faMastodon,
  faBluesky,
  faNpm,
  faPhp,
  faPython,
  faVuejs,
  faWindows,
} from "@fortawesome/free-brands-svg-icons";
import {
  faAntlr,
  faIntellij,
  faKafka,
  faKotlin,
  faKubernetes,
  faNeo4j,
  faNginx,
  faScrum,
  faSpring,
  faSwagger,
  faTs,
  faVscode,
} from "@/icons";

config.autoAddCss = false;

library.add(
  faHome,
  faList,
  faGraduationCap,
  faProjectDiagram,
  faBook,
  faMicrochip,
  faDatabase,
  faServer,
  faEnvelope,
  faMapMarkerAlt,
  faFlag,
  faTerminal,
  faCode,
  faFile,
  faLinkedin,
  faMastodon,
  faBluesky,
  faDiscord,
  faAngular,
  faVuejs,
  faPython,
  faJs,
  faNpm,
  faJava,
  faPhp,
  faLinux,
  faWindows,
  faGitAlt,
  faGithub,
  faGithubSquare,
  faGitlab,
  faDocker,
  faLock,
  //@ts-ignore
  faSpring,
  faTs,
  faKotlin,
  faNginx,
  faVscode,
  faAntlr,
  faKubernetes,
  faSwagger,
  faKafka,
  faIntellij,
  faNeo4j,
  faScrum,
);

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component("font-awesome-icon", FontAwesomeIcon);
});